name: rtos-build

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

on: [pull_request]

jobs:
  rtos-build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        github-server-url: https://github.com/dogusyuksel/rtos_hal_stm32
        lfs: true

    - uses: actions/checkout@v4
      with:
        github-server-url: https://github.com/dogusyuksel/embedded_docker.git
        lfs: true
        path: docker
    
    - name: rtos bitbake Build Check
      run: |
        ls -al && tree

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Project Docker
      uses: docker/build-push-action@v5
      with:
        load: true
        tags: |
          ${{ secrets.DOCKER_REPO }}:master
        context: .
        file: docker/Dockerfile
        pull: true
        push: false
        provenance: false

    - name: rtos bitbake Build Check
      run: |
        ./docker/sudo_run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/build && ./build_all.sh"
